# Generated by Django 3.2.12 on 2022-02-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appImageA4', '0004_userimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='original_height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userimage',
            name='original_width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userimage',
            name='resize_height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userimage',
            name='resize_width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
